// src/components/completion.tsx
import { observer } from "mobx-react-lite";
import { useEffect } from "react";
import { store } from "../store/store";
import "./completion.scss";

export const Completion = observer(() => {
  if (!store.completion.isVisible) {
    return null;
  }

  return <li className="Completion">
    {store.completion.list.map(completion => <Element key={completion} value={completion}/> )}
  </li>;
});

const Element = observer(({ value }:{ value: string }) => {
  useEffect(() => window.scrollTo(0, document.body.scrollHeight));

  return <div className={store.completion.selected === value ? "active" : ""}>
    {value}
  </div>;
});

// src/components/Completion.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  export let index: number
  export let completions: string[]

  onMount(() => {
    window.scrollTo(0, document.body.scrollHeight)
  })
</script>

<li class="completions">
  {#each completions as completion, i}
    <div class={i === index ? 'active' : ''}>
      {completion}
    </div>
  {/each}
</li>

<style lang="scss">
  .completions {
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    column-gap: 10px;
  }

  .active {
    background-color: #aaa;
    color: #111;
  }
</style>
