// src/components/Completion.tsx
import { useEffect } from "react";
import "./Completion.scss";

export function Completion({ list, index }:{ list: string[], index: number}) {
  useEffect(() => window.scrollTo(0, document.body.scrollHeight));

  return <li className="Completion">
    {list.map((completion, i) => <div key={i} className={i === index ? "active" : ""}>
      {completion}
    </div>)}
  </li>;
}

// src/components/Completion.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  export let index: number
  export let completions: string[]

  onMount(() => {
    window.scrollTo(0, document.body.scrollHeight)
  })
</script>

<li class="completions">
  {#each completions as completion, i}
    <div class={i === index ? 'active' : ''}>
      {completion}
    </div>
  {/each}
</li>

<style lang="scss">
  .completions {
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    column-gap: 10px;
  }

  .active {
    background-color: #aaa;
    color: #111;
  }
</style>
