// src/components/LinePrefix.svelte
<script lang="ts">
  const user = 'root'
  const domain = 'adamzielonka.pro'
  export let path = '~'
</script>

<span class="user">{user}@{domain}</span>:<span class="path">{path}</span>#

<style>
  span {
    font-weight: bold;
  }

  .user {
    color: lawngreen;
  }
  .path {
    color: #f0f;
  }
</style>

// src/components/LinePrefix.tsx
import "./LinePrefix.scss";

type Prefix = {
  user?: string,
  domain?: string,
  path?: string
}

export function LinePrefix({user = "root", domain = "adamzielonka.pro", path = "~"}: Prefix) {
  return <span className="LinePrefix">
    <span className="user">{user}@{domain}</span>:<span className="path">{path}</span>#
  </span>;
}
