// src/Terminal.svelte
<script lang="ts">
  import Input from './components/Input.svelte'
  import Line from './components/Line.svelte'
  import Shutdown from './components/Shutdown.svelte'
  import { font } from './store/font'
  import { lines } from './store/lines'
  import { freeze, isProcessing, shutdown } from './store/system'
</script>

{#if $shutdown}
  <Shutdown />
{:else}
  <div style={`font-family: ${$font}`}>
    <ul>
      {#each $lines as line}
        <Line value={line.text} command={line.command} blink={line.blink} />
      {/each}

      {#if !$isProcessing && !$freeze}
        <Input />
      {/if}
    </ul>
  </div>
{/if}

<style>
  div {
    float: left;
  }

  ul {
    list-style: none;
  }
</style>

// src/components/Terminal.tsx
import { observer } from "mobx-react-lite";
import { store } from "../store/store";
import { Shutdown } from "./Shutdown";
import { Line } from "./Line";
import { Input } from "./Input";
import "./Terminal.scss";
import { Completion } from "./Completion";

export const Terminal = observer(() => {
  if (store.system.shutdown) {
    return <Shutdown/>;
  }

  return <div className="Terminal" style={{fontFamily: store.style.font}}>
    <ul>
      {store.lines.value.map((line, i) => <Line key={i} line={line}/> )}
      {store.system.isInputAllowed && <Input/>}
      <Completion/>
    </ul>
  </div>;
});
