// src/Terminal.svelte
<script lang="ts">
  import Input from './components/Input.svelte'
  import Line from './components/Line.svelte'
  import Shutdown from './components/Shutdown.svelte'
  import { font } from './store/font'
  import { lines } from './store/lines'
  import { freeze, isProcessing, shutdown } from './store/state'
</script>

{#if $shutdown}
  <Shutdown />
{:else}
  <div style={`font-family: ${$font}`}>
    <ul>
      {#each $lines as line}
        <Line {line} />
      {/each}

      {#if !$isProcessing && !$freeze}
        <Input />
      {/if}
    </ul>
  </div>
{/if}

<style>
  div {
    float: left;
  }

  ul {
    list-style: none;
  }
</style>

// src/Terminal.jsx
import React from 'react'
import { store } from './store'
import { observer } from 'mobx-react-lite'
import { Line } from './components/Line'
import { Shutdown } from './components/Shutdown'
import { InputLine } from './components/Input'

function Terminal() {
  const { lines, shutdown, font } = store

  if(shutdown) return <Shutdown />
  
  return <div style={{ fontFamily: font }}>
    <ul>
      {lines.map((line, index) => <Line key={index} {...line} />)}
      <InputLine/>
    </ul>
  </div>
}

export default observer(Terminal)
